# Site settings
title: Dayoungs' DevDev
description: 'Hi :)'
url: 'https://dayowoo.github.io'
baseurl: ''
# google_analytics: 'UA-XXXXXX-X'
disqus_shortname: 'dayowoo'

author:
  name: 'dayowoo'
  email: kkbo5222@gmail.com
  instagram_username: dayowo_o
  facebook_username: dayowoo
  github_username:  dayowoo
  # linkedin_username:  none

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed
